package net.cloudburo.drools.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Offer() {
    }




}